version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: urlshortener-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: urlshortener-backend
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=urlshortener
      - MONGO_COLLECTION=urls
      - SHORT_BASE_URL=http://localhost:3000
    depends_on:
      - mongo
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: urlshortener-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  mongo_data: